### ISSUE TITLE
Attempting to stream byte range for LCP encrypted audiobooks results in full book download

### ISSUE THREAD

**Issue by mutterback** [edrlab/lcp-server#4]
Hi - looking for some assistance here with my colleagues

We are attempting to download a byte range of an LCP'd audiobook. We've opened access to byte range streaming on our server. Our goals are:
- to enable users to start listening to a partial download without waiting for the full book to complete
-  to give users a partial download to start, 
-  to allow them to start and stop downloads, 
- and to preserve a partial download on their device and start listening if a user loses a connection mid download.

When we request the byte range with the API, we are getting the entire book download.

The documentation here suggests we should be able to do this:
https://github.com/readium/kotlin-toolkit/blob/develop/docs/guides/lcp.md

Platform: Kotlin / Android
LCP Server version: (I'll update, we should be on the latest)

Postman screen shot attached.

![postman-byte-range-request](https://github.com/user-attachments/assets/8920c21a-545d-4c34-bff4-cbaff74595a3)

**Comment by llemeurfr** [comment]
Indeed, this test HTTP Server may not be configured to accept byte range requests. We'll check that. The HTTP Server that serves the encrypted content is totally different from the HTTP Server which handles the REST API of the LCP Server.

**Comment by mocyeg** [comment]
@llemeurfr - we're using GCP object storage which [does appear to support](https://cloud.google.com/storage/docs/samples/storage-download-byte-range#storage_download_byte_range-go) byte range requests. with this configuration, we still get the full file downloading.

is there more configuration required that we may have missed?

**Comment by llemeurfr** [comment]
@mocuyeg, let's exchange real URLs on Slack then. We'll come back to Github with more info.

**Comment by mocyeg** [comment]
@llemeurfr @mutterback we were able to get byte range requests working end to end with GCP object storage. I'm not sure exactly what the issue was, but it seems to be working now.

I appreciate your willingness to help out

**Comment by mutterback** [comment]
Thank you all. -closing this
